### ISSUE TITLE
解压文件路径不能有空格？

### ISSUE THREAD

**Issue by SakuraLeanne** [insistime/qiao.plugin.zip#1]
如果路径包含空格 解压不成功

**Comment by uikoo9** [comment]
> 如果路径包含空格 解压不成功

麻烦提供一下使用代码，我这边试试

**Comment by SakuraLeanne** [comment]
您好，我这边直接使用的是您的代码 给您开一下截图吧
![unzip](https://user-images.githubusercontent.com/37390452/50869457-05630e00-13ef-11e9-9826-1603a7d88fef.PNG)
![default](https://user-images.githubusercontent.com/37390452/50869459-072cd180-13ef-11e9-84ad-f0c6ff6455c3.PNG)

**Comment by uikoo9** [comment]
已经修改md文件，多谢关注~

另外，cli命令行修改为了qzip，知晓

![22](https://user-images.githubusercontent.com/10345351/50883132-1da05080-1422-11e9-947c-f860cf78a781.jpg)

**Comment by uikoo9** [comment]
你好，可以更新到0.3.0版本

主要是优化了cli下的交互和显示

![11](https://user-images.githubusercontent.com/10345351/50890550-63b2df80-1435-11e9-8e51-408c0642a98d.jpg)
![22](https://user-images.githubusercontent.com/10345351/50890551-644b7600-1435-11e9-9adf-6c575bd9a8c4.jpg)
